### ISSUE TITLE
ActionView::Template::Error (undefined method `new_record?' for nil:NilClass)

### ISSUE THREAD

**Issue by macsrok** [nickcharlton/administrate-field-nested_has_many#1]
Hello,

I'm trying to get this to work with no luck. I have a Service model that has many ServicePrices. Unfortunately I'm unable to get this to work correctly. Below I  have supped the error trace and my dashboards. Could you please advise. Thanks in advance.
## Error Log

Rendered layouts/admin/application.html.erb (106.6ms)
Completed 500 Internal Server Error in 166ms (ActiveRecord: 3.0ms)

ActionView::Template::Error (undefined method `new_record?' for nil:NilClass):
     7:   <% end -%>
     8:
     9:   <%# TODO I18n %>
    10:   <%= link_to_remove_association "Remove #{field.associated_class_name.titleize}", f %>
    11: </div>
  cocoon (1.2.9) lib/cocoon/view_helpers.rb:29:in`link_to_remove_association'
  administrate-field-nested_has_many (0.0.2) app/views/fields/nested_has_many/_fields.html.erb:10:in `___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_field_nested_has_many_______app_views_fields_nested_has_many__fields_html_erb__800476393924705469_70324067220000'
  actionview (4.2.1) lib/action_view/template.rb:145:in`block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in`instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:339:in`render_partial'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in`render_partial'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:32:in`render'
  administrate-field-nested_has_many (0.0.2) app/views/fields/nested_has_many/_form.html.erb:4:in `block in ___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_field_nested_has_many_______app_views_fields_nested_has_many__form_html_erb__1192621737250090986_70324060020100'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in`block in capture'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in`capture'
  actionview (4.2.1) lib/action_view/helpers/form_helper.rb:714:in `fields_for'
  actionview (4.2.1) lib/action_view/helpers/form_helper.rb:1598:in`fields_for'
  administrate-field-nested_has_many (0.0.2) app/views/fields/nested_has_many/_form.html.erb:3:in `___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_field_nested_has_many_______app_views_fields_nested_has_many__form_html_erb__1192621737250090986_70324060020100'
  actionview (4.2.1) lib/action_view/template.rb:145:in`block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in`instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:339:in`render_partial'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in`render_partial'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:32:in`render'
  administrate (0.2.0) app/helpers/administrate/application_helper.rb:5:in `render_field'
  administrate (0.2.0) app/views/administrate/application/_form.html.erb:35:in`block (2 levels) in ___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application__form_html_erb___2873134874680792653_70324128246040'
  administrate (0.2.0) app/views/administrate/application/_form.html.erb:33:in `each'
  administrate (0.2.0) app/views/administrate/application/_form.html.erb:33:in`block in ___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application__form_html_erb___2873134874680792653_70324128246040'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:200:in`with_output_buffer'
  actionview (4.2.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.1) lib/action_view/helpers/form_helper.rb:444:in`form_for'
  administrate (0.2.0) app/views/administrate/application/_form.html.erb:17:in `___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application__form_html_erb___2873134874680792653_70324128246040'
  actionview (4.2.1) lib/action_view/template.rb:145:in`block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in`instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:339:in`render_partial'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
  actionview (4.2.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in`render_partial'
  actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  administrate (0.2.0) app/views/administrate/application/new.html.erb:27:in`___sers_joesimms__rbenv_versions_______lib_ruby_gems_______gems_administrate_______app_views_administrate_application_new_html_erb__195939193033015907_70324077062700'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in`instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in`render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in`render_with_layout'
  skylight (0.10.3) lib/skylight/probes/action_view.rb:32:in `block in render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
  skylight (0.10.3) lib/skylight/probes/action_view.rb:31:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in`render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in`render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in`_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in`render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in`render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in`block in ms'
  /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in`ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in`cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in`render'
  administrate (0.2.0) app/controllers/administrate/application_controller.rb:26:in `new'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in`call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in`call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in`_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in`process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in`block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in`process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in`call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in`serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in`each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in`call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in`catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in`call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in`call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in`call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in`call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in`_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in`block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in`call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in`call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in`block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in`tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in`call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/runtime.rb:18:in`call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in`call'
  rack-contrib (1.4.0) lib/rack/contrib/sendfile.rb:103:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in`call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in`call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in`catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  eventmachine (1.2.0.1) lib/eventmachine.rb:1076:in`call'
  eventmachine (1.2.0.1) lib/eventmachine.rb:1076:in `block in spawn_threadpool'

  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (12.0ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.3ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (89.4ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/layout.erb (92.0ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.6ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/layouts/inlined_string.erb (2.8ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/layouts/inlined_string.erb (2.2ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/layouts/inlined_string.erb (2.8ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (81.0ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/layouts/javascript.erb (83.1ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/layouts/javascript.erb (2.6ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.6ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/layouts/javascript.erb (6.8ms)
  Rendered /Users/joesimms/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (173.1ms)
## services_controller.rb

`module Admin
  class ServicesController < Admin::ApplicationController
  end
end`
## service_prices_controller.rb

`module Admin
  class ServicePricesController < Admin::ApplicationController
  end
end`
## service_dashboard.rb

`require "administrate/base_dashboard"

class ServiceDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    name: Field::String,
    service_category: Field::BelongsTo,
    type: EnumField,
    service_prices: Field::NestedHasMany.with_options(skip: :service),
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :name,
    :type
  ]

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = ATTRIBUTE_TYPES.keys

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :name,
    :type,
    :service_category,
    :service_prices
  ]

end
`
## service_price_dashboard.rb

`require "administrate/base_dashboard"

class ServicePriceDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    name: Field::String,
    service_id: Field::BelongsTo,
    cost: Field::Number,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :name,
    :cost
  ]

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = ATTRIBUTE_TYPES.keys

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :name,
    :cost
  ]

end
`

**Comment by phaza** [comment]
It's because you're missing the `accepts_attributes_for :service_prices` in your Service model.

**Comment by prem-prakash** [comment]
I have same error here, but I am trying to use it in a HasOne relation

**Comment by axelclark** [comment]
I think this can be closed.  I had the same issue and phaza's suggestion fixed it for me.

**Comment by michalvalasek** [comment]
I confirm that adding `accepts_nested_attributes_for` to the parent model solves the issue.

**Comment by adrianchinghc** [comment]
@axelclark @michalvalasek Did you guys get this working for you? The link to add is there for mine but nothing happens when I click on the link.

**Comment by allthesignals** [comment]
@adrianchinghc same.

**Comment by badosu** [comment]
@macsrok Do you still have this problem? The last version on `master` (1.0.0) has not been released on rubygems yet was tested on the last rails and administrate versions.

**Comment by orthodoX** [comment]
> It's because you're missing the `accepts_attributes_for :service_prices` in your Service model.

Thanks man, I had  exactly this problem 👍

**Comment by sedubois** [comment]
Despite having `accepts_nested_attributes_for`, when trying to load the creation form (URL http://localhost:3000/admin/posts/new) I get the error `undefined method 'new_record?' for nil:NilClass`. This is thrown at [`cocoon (1.2.14) lib/cocoon/view_helpers.rb:29`](https://github.com/nathanvda/cocoon/blob/master/lib/cocoon/view_helpers.rb#L29).

I use Globalize 5.3.0 + Adminstrate 0.12.0 + administrate-field-nested_has_many 1.1.0 + cocoon 1.2.14 with the administrate config below. Would anyone have an idea?

```rb
# app/models/post.rb
class Post < ApplicationRecord
  translates :title, :excerpt, :tags, :original_url, :legacy_urls, :published, :published_at, :content, versioning: :paper_trail
  accepts_nested_attributes_for :translations, allow_destroy: true
  ...
end

# app/dashboards/post_dashboard.rb
class PostDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    translations: Field::NestedHasMany.with_options(class_name: "Post::Translation"),
    ...
  }
  FORM_ATTRIBUTES = %i[
    translations
    ...
  ]
end
```

**Comment by sedubois** [comment]
OK my issue was because the associated model was namespaced: `Post::Translation`, and as detailed in [this other thread](https://github.com/nathanvda/cocoon/issues/569#issuecomment-545392738), `administrate-field-nested_has_many` infers an `association_name` of `post/translations` instead of `translations`. I had to extend `NestedHasMany` in my code and redefine `association_name` to return `translations` instead of `post_translations`.

**Comment by nickcharlton** [comment]
I'm going to close this, as part of the original issue is solved with `accepts_nested_attributes_for` and the other being a namespacing which we're  looking at in #24.

**Comment by tomichal** [comment]
Shouldn't this gem be decorating the model with `accepts_nested_attributes_for`?
