### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by phaza** [nickcharlton/administrate-field-nested_has_many#3]
I'm getting this error when I try to add it to a rails5 project.

> There was a LoadError while loading administrate-field-nested_has_many.gemspec: 
> cannot load such file -- administrate/field/has_many from
>   /home/vagrant/.bundle/ruby/2.3.0/administrate-field-nested_has_many-a10b525ecdce/administrate-field-nested_has_many.gemspec:3:in `<main>'
> 
> Does it try to require a relative path? That's been removed in Ruby 1.9.

Gemfile:

``` ruby
gem 'administrate', github: 'greetpoint/administrate', branch: 'rails5'
gem "administrate-field-nested_has_many", github: 'phaza/administrate-field-nested_has_many'
```

Reason for using forks is to get rails5 support.
I got nested_has_many to work by hardcoding the version in the gemspec (so it doesn't need to require anything to resolve dependencies), I assume the reason it barfs is because administrate isn't loaded at this time in bundler.

**Comment by bryanwoods** [comment]
@phaza Were you able to work around this issue? I can develop with this gem just fine if I have `administrate` loaded on my system, but haven't found a clean way of deploying without resorting to hacks.

**Comment by badosu** [comment]
@phaza @bryanwoods  Do you still have this problem? The last version on `master` (1.0.0) has not been released on rubygems yet was tested on the last rails and administrate versions.

**Comment by phaza** [comment]
@bryanwoods @badosu Nah sorry, not doing rails dev anymore.

**Comment by bryanwoods** [comment]
@badosu I migrated the project off administrate, sorry

**Comment by badosu** [comment]
@nickcharlton This can be closed as well
