### ISSUE TITLE
This doesn't support namescoped names in models

### ISSUE THREAD

**Issue by willian** [nickcharlton/administrate-field-nested_has_many#8]
I have `List` and `List::Item` models, and something like `has_many :items, class_name: 'Item::List` and `belongs_to :list` respectively.

So, what do you think about this fork/PR?
https://github.com/phaza/administrate-field-nested_has_many/pull/1

**Comment by madakopihub** [comment]
any updates?

**Comment by sedubois** [comment]
The PR seems to have been made on the fork instead of here.
