### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by NedelescuVlad** [nickcharlton/administrate-field-nested_has_many#9]
Hi there,

Would it be possible to offer a rails 5 version of this gem? Great work on administrate by the way 👍

**Comment by NedelescuVlad** [comment]
I've ended up forking the repo and making some trivial changes in the .gemspec file. Here's the repo if anyone else come across this problem:
https://github.com/NedelescuVlad/administrate-field-nested_has_many

**Comment by badosu** [comment]
@nickcharlton This issue can be closed by #10 and #11

**Comment by nickcharlton** [comment]
Ah, great! Thanks for pointing it out.
